name: gen

on:
  pull_request:
    branches: [ master ]

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Generate code
      uses: docker://ghcr.io/pipe-cd/codegen@sha256:c3a50d18213a033f4421b738cccb4ac35fd422cd5f20593c72fbbf8df2c7e11e #v0.47.0-38-gfb30821
      with:
        entrypoint: ./tool/codegen/codegen.sh
        args: /github/workspace
    - name: Show Git status
      shell: bash
      run: git status
    - name: Validate
      shell: bash
      run: test -z "$(git status --porcelain)"
